Add user search functionality
dmranck/ticketutil pull request #75
Opened 2022-12-29 16:00 UTC by Archana-PandeyM

Added a private method _get_username_from_email(). This method will accept an email as argument and returns the username associated to provided emaiID.
This method is then being utilized by add_watcher and remove_watcher function to get the username of watcher(in case email is passed as an argument).

2023-01-03 14:21 UTC, dmranck commented
Adding @advaitgupte04 as a reviewer

2023-01-04 20:32 UTC, dmranck requested changes
@Archana-PandeyM , this looks great! I ran through an example with the three types of Jira usernames we had discussed and they all worked for adding and removing watchers. I also tried a fake Jira email address and the error handling in _get_username_from_email handled it well, spitting out appropriate error messages, but continuing on with the execution.

I added a few small comments about indentation level and logging messages, but other than that, I would be ready to merge this soon. Thanks for working on this!

2023-01-04 20:32 UTC, dmranck commented on ticketutil/jira.py
> +            # username for watcher .
Back up the indentation one tab level to be in-line with line 386.

2023-01-04 20:32 UTC, dmranck commented on ticketutil/jira.py
> +            :return: username
Indentation level should be in-line with line 525.

2023-01-04 20:32 UTC, dmranck commented on ticketutil/jira.py
> +            logger.debug("Get ticket content: status code: {0}".format(r.status_code))
"Get ticket content" should probably be changed to "Get username"

2023-01-04 20:32 UTC, dmranck commented on ticketutil/jira.py
> +                logger.error("user with email {0} could not be found".format(email))
Change "user" to "User", just because all other logging messages start with a capital letter

2023-01-06 15:50 UTC, dmranck approved these changes

2023-01-06 21:37 UTC, advaitgupte04 commented
@dmranck Archana's PR looks good to me. Tested the below scenarios: 
1. Added myself to ticket as watcher 
2. Added Andrew's username to ticket as watcher 
3. Added Jan's username to ticket as watcher
4. Tried adding a wrong username as watcher and got appropriate error

2023-01-13 16:21 UTC, merged